Sprint 2/step 2
MaksimSyasin/react-burger pull request #3
Opened 2023-04-23 23:30 UTC by MaksimSyasin

2023-04-24 04:23 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Используется redux;
- Реализован DnD;

### **Но есть несколько замечаний, которые нужно исправить:**

- <https://disk.yandex.com/i/k1Ijgi9e58uCpw> - Лучше скрыть и написать перетащите булки/ингредиенты;

- По макету у булок должна быть приписка `(верх)` и `(низ)`. <https://disk.yandex.com/i/Pmha_GVN4kh7lw>;

- У вас неправильно работает DnD, нельзя перетащить ингредиенты на первое и последнее место: <https://disk.yandex.com/i/WS5BHPpRy05csA>, советую обратиться за помощью к наставнику;

- Вам нужно выполнять запрос `POST /orders` (Он описан в прошлом задание про Контекст). В запросе `POST /orders` нужно чтобы id у булок были в начале и в конце массива, а id ингредиентов между ними;

- со временем приложение будет разрастаться, появится новый функционал, если все будет в одном редьюсере он станет слишком большим, разделите один большой редьюсер на несколько, обрабатывающие данные одной предметной области (одного "домена"), например

  - загрузка данных ингредиентов
  - отправка заказа
  - работа конструктора
  - открытие модального окна ингредиента

  Для объединения редьюсеров используйте combineReducers
  <https://redux.js.org/api/combinereducers>

- Следует разделить экшены по файлам, на нас есть несколько задач (доменных областей) не связанных между собой - загрузка ингредиентов, оформление заказа, работа конструктор. Лучше, что бы экшены относящиеся к решению каждой были описаны в своем файле, т.к. приложение со времени будет развиваться, будет добавлять новый функционал и плохо, если придется все экшены описывать в одном файле, он будет слишком большой

  В текущем приложении можно разделить на следующие файлы:

  - загрузка данных ингредиентов
  - работа конструктора
  - открытие ингредиента в попапе
  - оформление заказа

- Если значения нет, то нужно использовать null, а не пустой объект.

- Везде где есть `Object.keys` проверки, их нужно убрать (после исправления `{}`, `{}` нужно заменить на `null` ).

### **Сделает код лучше:**

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-04-24 04:23 UTC, ArslanDev666 commented on src/components/App/app.jsx
> +  };
**Надо исправить:**

не совсем понимаю почему вы эту функцию сделали тут, а не в `burger-constructor`.

2023-04-24 04:23 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +    let { bun } = useSelector(state => state.ingredients);
**Можно лучше:**

лучше написать вот так: 

```js
const ingredientsInConstructor = useSelector(state => state.ingredients.ingredientsInConstructor);
const bun = useSelector(state => state.ingredients.bun);
```

https://habr.com/ru/articles/722444/

2023-04-24 04:23 UTC, ArslanDev666 commented on src/components/burger-constructor/custom-constructor-element/custom-constructor-element.jsx
> +function CustomConstructorElement({text, price, thumbnail, handleDelete, index}) {
**Надо исправить:**

Для этого компонента так же нужно описать PropTypes.

2023-04-24 04:23 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +                                <li key={crypto.randomUUID()} >
**Надо исправить:**

Не стоит генерировать значение в `key`, вам нужно присваивать уникальный `id` в экшене (при добавлении ингредиента), а потом его использовать в `key`. Иначе, у вас практически постоянно будет перерендер всех ингредиентов, при ререндере компонента `burger-constructor`;

2023-04-24 04:23 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +                            ingredientsInConstructor &&
**Надо исправить:**

Тут всегда будет `true`, поэтому проверка избыточна, и её можно убрать.

2023-04-24 04:23 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +    const calcPrice = () => {
**Можно лучше:**

Лучше обернуть в `useMemo`, и использовать как значение, а не функцию

2023-04-24 04:23 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +                        onClick={() => { createOrder() }}
**Надо исправить:**

Тут можно просто написать `onClick={createOrder}`

2023-04-24 04:23 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  }, [dispatch])
**Можно лучше:**

лучше перенести в `app`, сейчас это не критично, но в будущем может помочь)

2023-04-24 04:23 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  const {ingredients, ingredientsFailed} = useSelector(state => state.ingredients);
**Можно лучше:**

Лучше разделить на отдельные переменные.

2023-04-24 04:23 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  const [ingredientInModal, setIngredientInModal] = useState()
**надо исправить:**

Для модального окна ингредиента, вы также используйте `redux`, значит должны брать эту информацию из него, а не хранить в локальном стейте.

2023-04-24 04:23 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +                                if (item.type === 'bun') {
**Можно лучше**

Лучше в компоненте делать filter по массиву, а потом отображать полученный массив.

Например:

```js
const buns = useMemo(data.filter((item) => item.type === 'bun'), [data]);
const mains = useMemo(data.filter((item) => item.type === 'main'), [data]);
const sauces = useMemo(data.filter((item) => item.type === 'sauce'), [data]);

return (
   ....................
   {buns.map(....................)}
   ..................
)
```

А не располагать фильтрацию в самом jsx

2023-04-24 04:23 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +                    </div>
**Можно лучш:**

у каждой категории ингредиентов дублируется верстка, лучше вынести отдельный компонент ingredients-category и переиспользовать его

2023-04-24 04:23 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +                        {ingredients &&
**Надо исправить:**

Здесь и далее.

Проверка избыточна, её можно убрать.

2023-04-24 04:23 UTC, ArslanDev666 commented on src/components/burger-ingredients/ingredient-item/ingredient-item.jsx
> +function IngredientItem({ item, onIngrediantClick, ingredientsCounter }) {
**Надо исправить:**

в `propTypes` описаны не все пропсы,

2023-04-24 04:23 UTC, ArslanDev666 commented on src/index.jsx
> +const store = createStore(rootReducer, enhancer);
**Можно лучше:**

Это лучше вынести в отдельный файл, в папку `services`

2023-04-24 04:23 UTC, ArslanDev666 commented on src/index.jsx
> +  <>
**Надо исправить:**

Верните `StrictMode`, он помогает отлавливать ошибки)

2023-04-24 04:23 UTC, ArslanDev666 commented on src/services/actions/burger-constructor.js
> +  }
**Надо исправить:**

Вынесите базовый адрес сервера `https://norma.nomoreparties.space/api` сервера в константу в отдельный файл, а адрес эндпоинта можно оставить в самой функции запроса `${BURGER_API_URL}/ingredients`

Проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```js
const checkResponse = res => {
  return res.ok ? res.json() : res.json().then(err => Promise.reject(err));
};
```

`fetch(someUrl).then(checkResponse)`

**Можно лучше:**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```js
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}
```

и разместить их в отдельном файле `utils/burger-api.js`, а не описывать запросы в самом компоненте

2023-04-24 04:23 UTC, ArslanDev666 commented on src/services/reducers/burger-constructor.js
> +    bun: {},
**Надо исправить:**

Если значения нет, то нужно использовать null, а не пустой объект.

2023-04-24 04:23 UTC, ArslanDev666 commented on src/services/reducers/burger-constructor.js
> +    ingredientModalActive: {},
**Надо исправить:**

Если значения нет, то нужно использовать null, а не пустой объект.

2023-04-26 19:04 UTC, MaksimSyasin commented on src/components/burger-constructor/burger-constructor.jsx
> +                                <li key={crypto.randomUUID()} >
Я не совсем понимаю, что именно нужно сделать

2023-04-26 19:05 UTC, MaksimSyasin commented on src/components/burger-constructor/burger-constructor.jsx
> +                            ingredientsInConstructor &&
Без этой проверки у меня вылетают ошибка Cannot read properties of null (reading 'map')

2023-04-27 08:10 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +                                <li key={crypto.randomUUID()} >
Сейчас при ререндере, вы генерируете в `key` каждый раз новое значение, соответсвенно `react` это воспринимает как сигнал к перерендеру этого элемента, т.к. значение `key` изменилось.  Это может немного ухудшить производительность приложения)

2023-04-27 08:26 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец!**

- Практически все замечания были исправлены;

### **Отметил замечания в коде, которые нужно исправить.**

2023-04-27 08:26 UTC, ArslanDev666 commented on src/services/reducers/ingredients.js
> +    ingredientsInConstructor: null,
**Надо исправить:**

тут должно быть не `null`, а пустой массив.

2023-04-27 08:26 UTC, ArslanDev666 commented on src/services/reducers/ingredients.js
> +                ingredientsInConstructor: false
**Надо исправить:**

Тут должен быть пустой массив а не булево значение

2023-04-27 08:26 UTC, ArslanDev666 commented on src/services/reducers/ingredients.js
> +                bun: false,
**Надо исправить:**

Тут должен быть `null` а не булево значение

2023-04-27 08:26 UTC, ArslanDev666 commented on src/services/reducers/order.js
> +}
Вам не нужно сохранять заказы в редаксе, т.к. вы их будете получать через api) Лучше хранить 1 заказ, и при закрытии модального окна, очищать заказ.

```js
const initialState = {
    order: null
}

export const orderReducer = (state = initialState, action) => {
    switch (action.type) {
        
        case SET_ORDER: {
            return {
              ...state,
              order: action.order,
            };
        }
        case RESET_ORDER: {
            return {
              ...state,
              order: null,
            };
        }

        default: {
            return state;
        }
    }
}
```

2023-04-27 08:26 UTC, ArslanDev666 commented on src/services/reducers/modal.js
> +                ingredientModalActive: {}
**Надо исправить:**

Если значения нет, то нужно использовать null, а не пустой объект.

2023-04-27 08:26 UTC, ArslanDev666 commented on src/services/actions/ingredients.js
> +import { BURGER_API_URL } from "../../components/constants";
**Можно лучше:**

Лучше переместить в папку `utils`, а не `components`

2023-04-27 08:26 UTC, ArslanDev666 commented on src/components/burger-ingredients/ingredient-item/ingredient-item.jsx
> +    ingredientsCounter: PropTypes.object
По хорошему тут нужно полное описание, а не `PropTypes.object`, но с учётом того, что вы скоро перейдёте на TS, думаю никто не расстроится если здесь будет `PropTypes.object`.

2023-04-27 08:26 UTC, ArslanDev666 commented on src/services/reducers/modal.js
> +    ingredientModalActive: null,
**Можно лучше:**

Лучше переименовать просто в `ingredient` или `ingredientDetail`;

2023-04-27 17:36 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания были исправлены;

2023-07-15 15:51 UTC, merged